using Microsoft.EntityFrameworkCore;

namespace Btec_Website.Models
{

    public class ApplicationDbContext : DbContext
    {
        public DbSet<User> Users { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Course> Courses { get; set; }

        string ConnectionString =
        "Data Source=RUFUS\\SQLEXPRESS;Initial Catalog=SMS;Integrated Security=True;Trust Server Certificate=True";

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(ConnectionString);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<UserCourse>()
                .HasKey(uc => new { uc.UserId, uc.CourseId });

            // Configure the Course entity
            modelBuilder.Entity<Course>(entity =>
            {
                entity.Property(e => e.Id)
                    .ValueGeneratedOnAdd(); // This configures the Id property to be auto-generated by the database
            });

            // Other entity configurations
        }

        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
         : base(options)
        {
        }
    }
}
